### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by phcollin** [Kribouille/JXSProject#2]

**Comment by phcollin** [comment]
- [ ] Explorateur de fichiers (possibilité de supprimer, renommer, déplacer ou ajouter des fichiers)
- [ ] Interface intuitive (affichage de la taille, des droits et des partages)
- [ ] Possibilité de partager ses fichiers avec un autre utilisateur
- [ ] Afficher l'espace disponible (de façon dynamique)
- [ ] Afficher la hiérarchie des deux Clouds
- [ ] Notifier l'utilisateur des modifications du Cloud
- [ ]
